<!DOCTYPE html>
<html lang="en"><!-- Basic -->
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">   
   
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
 
     <!-- Site Metas -->
    <title>Live Dinner Restaurant - Responsive HTML5 Template</title>  
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css">    
	<!-- Site CSS -->
    <link rel="stylesheet" href="css/style.css">    
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="css/responsive.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="css/custom.css">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<?php include "header.php"; ?>	

<body>
	<!-- Start header -->
	<!-- <header class="top-navbar">
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<div class="container">
				<a class="navbar-brand" href="index.html">
					<img src="images/logo.png" alt="" />
				</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars-rs-food" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
				  <span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbars-rs-food">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item"><a class="nav-link" href="index.html">Home</a></li>
						<li class="nav-item"><a class="nav-link" href="menu.html">Menu</a></li>
						<li class="nav-item"><a class="nav-link" href="about.html">About</a></li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" id="dropdown-a" data-toggle="dropdown">Pages</a>
							<div class="dropdown-menu" aria-labelledby="dropdown-a">
								<a class="dropdown-item" href="reservation.html">Reservation</a>
								<a class="dropdown-item" href="stuff.html">Stuff</a>
								<a class="dropdown-item" href="gallery.html">Gallery</a>
							</div>
						</li>
						<li class="nav-item active dropdown">
							<a class="nav-link dropdown-toggle" href="#" id="dropdown-a" data-toggle="dropdown">Blog</a>
							<div class="dropdown-menu" aria-labelledby="dropdown-a">
								<a class="dropdown-item" href="blog.html">blog</a>
								<a class="dropdown-item" href="blog-details.html">blog Single</a>
							</div>
						</li>
						<li class="nav-item"><a class="nav-link" href="contact.html">Contact</a></li>
					</ul>
				</div>
			</div>
		</nav>
	</header> -->
	<!-- End header -->
	
	<!-- Start All Pages -->
	<div class="all-page-title page-breadcrumb">
		<div class="container text-center">
			<div class="row">
				<div class="col-lg-12">
					<h1>Our Review Blog</h1>
				</div>
			</div>
		</div>
	</div>
	<!-- End All Pages -->
	
	<!-- Start blog -->
	<div class="blog-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="heading-title text-center">
						<!-- <h2>Our Review Blog</h2> -->
						<p><b>All the reviews are generated by our verified customers</b></p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4 col-md-6 col-12">
					<div class="blog-box-inner">
						<div class="blog-img-box">
							<img class="img-fluid" src="images/blog-img-01.jpg" alt="">
						</div>
						<div class="blog-detail">
							<h4>Review - 01</h4>
							<ul>
								<li><span>Posted by Tashfia Hossain</span></li>
								<li>|</li>
								<li><span>1st January, 2023</span></li>
							</ul>
							<p>Absolutely loved the food here! The flavors were spot on and the presentation was beautiful. Can't wait to come back!</p>
							<a class="btn btn-lg btn-circle btn-outline-new-white" href="#">Read More</a>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 col-12">
					<div class="blog-box-inner">
						<div class="blog-img-box">
							<img class="img-fluid" src="images/blog-img-02.jpg" alt="">
						</div>
						<div class="blog-detail">
							<h4>Review - 02</h4>
							<ul>
								<li><span>Posted by Rabeya Momo</span></li>
								<li>|</li>
								<li><span>27th November, 2022</span></li>
							</ul>
							<p>I had the best burger of my life here. Juicy, perfectly cooked, and topped with all the right ingredients. Highly recommend!</p>
							<a class="btn btn-lg btn-circle btn-outline-new-white" href="#">Read More</a>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 col-12">
					<div class="blog-box-inner">
						<div class="blog-img-box">
							<img class="img-fluid" src="images/blog-img-03.jpg" alt="">
						</div>
						<div class="blog-detail">
							<h4>Review - 03</h4>
							<ul>
								<li><span>Posted by Ashfaq Shourov</span></li>
								<li>|</li>
								<li><span>2nd July, 2019</span></li>
							</ul>
							<p>Amazing service and delicious food! We had a large group and they accommodated us so well. The seafood pasta was out of this world!</p>
							<a class="btn btn-lg btn-circle btn-outline-new-white" href="#">Read More</a>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 col-12">
					<div class="blog-box-inner">
						<div class="blog-img-box">
							<img class="img-fluid" src="images/blog-img-04.jpg" alt="">
						</div>
						<div class="blog-detail">
							<h4>Review - 04</h4>
							<ul>
								<li><span>Posted by Zakia Sharmin</span></li>
								<li>|</li>
								<li><span>5th May, 2021</span></li>
							</ul>
							<p>The sushi here was fantastic! The fish was incredibly fresh and the rolls were creative and beautifully presented. Will definitely be returning!</p>
							<a class="btn btn-lg btn-circle btn-outline-new-white" href="#">Read More</a>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 col-12">
					<div class="blog-box-inner">
						<div class="blog-img-box">
							<img class="img-fluid" src="images/blog-img-05.jpg" alt="">
						</div>
						<div class="blog-detail">
							<h4>Review - 05</h4>
							<ul>
								<li><span>Posted by Mina Rahman</span></li>
								<li>|</li>
								<li><span>27 February, 2022</span></li>
							</ul>
							<p>The pizza here is top-notch. The crust is thin and crispy, the sauce is flavorful, and the toppings were plentiful. So good!</p>
							<a class="btn btn-lg btn-circle btn-outline-new-white" href="#">Read More</a>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 col-12">
					<div class="blog-box-inner">
						<div class="blog-img-box">
							<img class="img-fluid" src="images/blog-img-06.jpg" alt="">
						</div>
						<div class="blog-detail">
							<h4>Review - 06</h4>
							<ul>
								<li><span>Posted by Nafee Hasan</span></li>
								<li>|</li>
								<li><span>22nd February, 2017</span></li>
							</ul>
							<p>This is hands down the best Indian food I've had in a long time. The naan was fluffy and warm, and the butter chicken was divine. I can't wait to try more dishes! </p>
							<a class="btn btn-lg btn-circle btn-outline-new-white" href="#">Read More</a>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 col-12">
					<div class="blog-box-inner">
						<div class="blog-img-box">
							<img class="img-fluid" src="images/blog-img-07.jpg" alt="">
						</div>
						<div class="blog-detail">
							<h4>Review - 07</h4>
							<ul>
								<li><span>Posted by Farzad Ahmed</span></li>
								<li>|</li>
								<li><span>15th January, 2023</span></li>
							</ul>
							<p>I was so impressed with the service here. The staff was friendly, attentive, and made sure we had everything we needed. Plus, our food came out quickly!</p>
							<a class="btn btn-lg btn-circle btn-outline-new-white" href="#">Read More</a>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 col-12">
					<div class="blog-box-inner">
						<div class="blog-img-box">
							<img class="img-fluid" src="images/blog-img-08.jpg" alt="">
						</div>
						<div class="blog-detail">
							<h4>Review - 08</h4>
							<ul>
								<li><span>Posted by Farhan Abid</span></li>
								<li>|</li>
								<li><span>18th April, 2021</span></li>
							</ul>
							<p>Ordered takeout from here and was blown away by how quickly it arrived. The food was still piping hot and delicious. Will definitely be ordering again!</p>
							<a class="btn btn-lg btn-circle btn-outline-new-white" href="#">Read More</a>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 col-12">
					<div class="blog-box-inner">
						<div class="blog-img-box">
							<img class="img-fluid" src="images/blog-img-09.jpg" alt="">
						</div>
						<div class="blog-detail">
							<h4>Review - 09</h4>
							<ul>
								<li><span>Posted by Humayra Ahmed</span></li>
								<li>|</li>
								<li><span>23rd October, 2022</span></li>
							</ul>
							<p>The delivery service here is top-notch. They were prompt, professional, and the food arrived in perfect condition. So happy with my experience!</p>
							<a class="btn btn-lg btn-circle btn-outline-new-white" href="#">Read More</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End blog -->
	
	
	<!-- Start Footer -->
	<?php include "footer.php"; ?>
	<!-- End Footer -->
	
	<a href="#" id="back-to-top" title="Back to top" style="display: none;"><i class="fa fa-paper-plane-o" aria-hidden="true"></i></a>

	<!-- ALL JS FILES -->
	<script src="js/jquery-3.2.1.min.js"></script>
	<script src="js/popper.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
    <!-- ALL PLUGINS -->
	
	<script src="js/jquery.superslides.min.js"></script>
	<script src="js/images-loded.min.js"></script>
	<script src="js/isotope.min.js"></script>
	<script src="js/baguetteBox.min.js"></script>
	<script src="js/form-validator.min.js"></script>
    <script src="js/contact-form-script.js"></script>
    <script src="js/custom.js"></script>
</body>
</html>